### ISSUE TITLE
spark cloud commands

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-cli#131]
This should replace `spark core rename` and `spark core remove` with `spark cloud rename` and `spark cloud remove` to have a general command for future dev kits like photon

**Comment by emilyrose** [comment]
I'm partial to the `device` keyword. What do you think?

**Comment by kennethlimcp** [comment]
sounds much better. I remember the older `spark cloud xxxx` remained due to backward compatibility with the old syntax used but it's time to remove them ;)

**Comment by kennethlimcp** [comment]
new implementation is `particle device xxxx`
