### ISSUE TITLE
revert CC3000 patch

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-cli#133]
@dmiddlecamp,

can we revert the CC3000 patch to this commit: https://github.com/spark/spark-cli/blob/10f65d1eba553df807457a5b90388704ea14b2bf/js/binaries/cc3000-patch-programmer.bin

See the forum thread for the same issue with the new patch not resolving the flashing green issue on new cores: https://community.spark.io/t/issue-connecting-wifi/9264/6

**Comment by sjlu** [comment]
+1

**Comment by dmiddlecamp** [comment]
I haven't had a chance to re-test this from a core with flashing-green, but I'll take your word on it and revert until I can test it.  Done!  Pushed version 0.4.93 with the reverted patcher.  The new one will be available as `cc3000_1_14`

Thanks,
David
