### ISSUE TITLE
Spark-cli install error

### ISSUE THREAD

**Issue by Voltezk** [spark/spark-cli#144]
Hi all,

I've been trying to download this package for quite a while, been looking everywhere for answers of problems of problems, trying to resolve this issue bit by bit, but I just couldn't get it to work in the end.

when I run :

npm install -g spark-cli

in the command prompt, I get :

![image](https://cloud.githubusercontent.com/assets/11069639/6261941/e47f42c6-b85d-11e4-8ec6-b7d001f4843c.png)

![image](https://cloud.githubusercontent.com/assets/11069639/6261948/f7a479de-b85d-11e4-81c8-0db43905d1d5.png)

![image](https://cloud.githubusercontent.com/assets/11069639/6261950/020b6ee6-b85e-11e4-90b5-ad554fceb966.png)

I have also tried running:

node-gyp configure
node-gyp build

but both gave me errors.. Maybe thats part of the issue?

Any help would be greatly appreciated!

**Comment by kennethlimcp** [comment]
Are you on Mac OSx?

**Comment by emilyrose** [comment]
This looks like a problem with nose-serialport on windows.

**Comment by kennethlimcp** [comment]
Definitely steering us to v1.5.0.

Initial test with Appveyor worked well. Haven't spun up windows boxs for 7 and 8.1 so hopefully something soon

**Comment by Voltezk** [comment]
Nope, I am on Windows 8.

**Comment by kennethlimcp** [comment]
If you are keen can you try this and let us know: 
https://community.spark.io/t/spark-cli-on-windows8-1-x64/9997/5

**Comment by Voltezk** [comment]
Changed it to * and ran npm install -g spark-cli again, but got the same error :/

Maybe its the problem with my directories? Ive been moving them around everywhere trying to fix this myself..

**Comment by kennethlimcp** [comment]
Sorry I might have messed up the command. It should be `npm install -g`

**Comment by Voltezk** [comment]
This is the error I get when I run the command:

![image](https://cloud.githubusercontent.com/assets/11069639/6279876/79d0e80a-b90a-11e4-821c-539f6e9ebc40.png)

**Comment by kennethlimcp** [comment]
@Voltezk, you don't look like you are in the `js` directory?

**Comment by Voltezk** [comment]
Sorry! Im still kinda new to this :/

I navigated to js and ran the command and it installed it just fine.

Could you explain what that just did?

**Comment by kennethlimcp** [comment]
Sure i'm happy to explain further!

1.) Changing the `node-serialport` version from **1.4.5** to * means "install the latest version" (1.5.0 in this case)

2.) cd to **js** directory is required as the `package.json` file to be read by the installer (npm) is inside

3.) You just did a manual installation instead of the automated `npm install -g spark-cli` which will pull the files from this repository. Reason being the version stated for `node-serialport` right now is **1.4.5**.


Can you verify that it installed properly with the command `spark --version`?

Also, can you tell us the Windows version and 32bit or 64bit? That will help us a lot!

**Comment by Voltezk** [comment]
Thanks for the explanation!

Unfortunately it still seems to have issues... spark --version under the js directory gives 'spark' is not a recognized as an internal or external command...

Also my Windows is 64 bit :)

**Comment by kennethlimcp** [comment]
Need some help from the javascript people now!

1.) @emilyrose, i presume this didn't end up in the `-g` since it's a locally installed directory?

2.) @Voltezk, in the mean time, you can cd to `bin` and use `node spark.js xxxxxxx` where `xxxxxx` are your commands`. eg. `node spark.js --version`

**Comment by Voltezk** [comment]
I get this when I run node spark.js --version in bin.

![image](https://cloud.githubusercontent.com/assets/11069639/6280255/f1289ec6-b90e-11e4-8841-acd0fb6ab2bf.png)

**Comment by kennethlimcp** [comment]
Conversation and troubleshooting moved here: https://community.spark.io/t/spark-cli-not-installing-on-windows/10096

**Comment by kennethlimcp** [comment]
@emilyrose, this can be closed with https://github.com/spark/spark-cli/pull/137 fix as well.

**Comment by emilyrose** [comment]
thanks!
