### ISSUE TITLE
~/.spark/spark.config.json permissions

### ISSUE THREAD

**Issue by osresearch** [spark/spark-cli#148]
Since the `~/.spark/spark.config.json` file has an access token that allows arbitrary access to a user's cores, it should be created with an explicit 600 mode rather than using the default umask to prevent another user on the system from stealing it.

**Comment by emilyrose** [comment]
@osresearch thank you for spotting this. Great point!

**Comment by kennethlimcp** [comment]
@emilyrose, that will apply to new `.json` file creations as well since users are free to add more cloud profiles using `spark cloud config`

**Comment by emilyrose** [comment]
@kennethlimcp definitely. Let me get a PR together & you can tell me what you think.

**Comment by emilyrose** [comment]
@osresearch, @kennethlimcp have a look at #149 and let me know what you think.

**Comment by kennethlimcp** [comment]
Not at all proficient in java/nodejs so you guys have definitely make a better call :)

**Comment by emilyrose** [comment]
I forgot to tag the PR, but a fix for this has been merged. Thanks @osresearch and @kennethlimcp for weighing in!
