### ISSUE TITLE
Validate profile before switching

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-cli#159]
We need to catch the exception of a `PROFILE_NAME.config.json` not existing and prompt the user to create one instead of simply switching to the profile name in the `profile.json` parameter without any checks

**Comment by dmiddlecamp** [comment]
When you switch to one that doesn't exist yet, it's created as you add override settings.

spark config foo
spark config foo apiUrl https://foo.biz/api

**Comment by kennethlimcp** [comment]
Yup yup..but it's not helping the user during typos :) except if you run `spark config identify` after running into issues.

1.) Without any override settings, it *should* validate against the available .json files
2.) With override settings, it means you are creating/edit a profile so no validation sounds ok

**Comment by dmiddlecamp** [comment]
hmm, sure, so a quick prompt with something like:

"Hey cool!  That profile doesn't exist yet, create it? [Y/n]"

**Comment by kennethlimcp** [comment]
Sounds good for sure! :+1:
