### ISSUE TITLE
no prompt to create new account

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-cli#161]
With the update of version **1.0.0** we are handling the Serial-port exception well but it doesn't allow `spark setup` to flow and enter the next step of setting up an account account instead.

See: https://community.spark.io/t/tutorial-local-cloud-1st-time-instructions-03-march-15/5589/92

**Comment by kennethlimcp** [comment]
@emilyrose,

1.) Perform a `spark logout`
2.) Use `spark setup` to create a new account
3.) You will reach a point where a core is not detected via Serial and hit any key 3 times till the exception exits
4.) The account creation will not be complete with this error:

```
Trying to login...
Could not get new access token:  User credentials are invalid
login error:  invalid_grant
Using the setting "username" instead 
Error setting up your core: Unable to login or create a new account
```

There are a couple of mixed issues that i am seeing:

1.) Spark setup is not recognizing that the username/password enter is not an available account.  It should and prompt you to re-enter the password in order to create a new account

Using **0.4.94** worked fine with: 

```
Setup your account

Could I please have an email address?  kennethlimcp1@gmail.com
and a password?  *******

Trying to login...
*********************************
      Please login - it appears your access_token may have expired
*********************************
Login failed, Lets create a new account!
confirm password  *******
```

2.) Spark login is

**Comment by kennethlimcp** [comment]
Trying to hunt this bug down and might be this PR changes for `login`: 

https://github.com/spark/spark-cli/commit/41ffc4ea2e5d87734709163f66578ad033ed9745

**Comment by kennethlimcp** [comment]
@emilyrose, giving this a bump.

See related issue happening: https://community.spark.io/t/local-cloud-dont-find-cores/10908/25

**Comment by dmiddlecamp** [comment]
bump, ran into this again today.

**Comment by dmiddlecamp** [comment]
fixed this because I need it right now
