### ISSUE TITLE
spark list online/offline

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-cli#163]
So with around 5-10 devices in my account, it's hard to spot the **offline/online** tag beside them!

Suggesting some new commands:

- spark list online

- spark list offline (might not be that helpful)

- spark list cores

- spark list photons

- spark list electrons

**Comment by dmiddlecamp** [comment]
ooh, great idea!  I agree the current online/offline formatting can be hard to read when you have a lot of devices.  This might also benefit from some style improvements as well, but the filters are a fun idea :) 

:+1:
