### ISSUE TITLE
`spark keys save` writes the PRIVATE key to core.pub.pem

### ISSUE THREAD

**Issue by m-mcgowan** [spark/spark-cli#190]
running `spark keys save 320020001847333531323135` against a photon gives

```
running dfu-util -d 2b04:d006 -a 1 -s 34:612 -U 320020001847333531323135
running openssl rsa -in 320020001847333531323135 -inform DER -pubout  -out 320020001847333531323135.pub.pem
```

The [devices spec](https://github.com/spark/spark-cli/blob/master/lib/deviceSpecs/specifications.js) lists only the location for the private key.

**Comment by kennethlimcp** [comment]
@m-mcgowan, isn't it reading the private key and generate the **pub.pem**?

**Comment by m-mcgowan** [comment]
yep. just realized this.
